# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.6.1
_src_path: https://github.com/epics-containers/ioc-template
description: A Generic IOC for use with accelerator controls diagnostics IOCs
git_platform: github.com
github_org: Bryn
name: ioc-diagnostics
repo_uri: git@github.com:8ryn/ioc-diagnostics.git
rtems: false
